movies/basic_app/urls.py
from django.urls import path
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.MovieListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.MovieDetailView.as_view(), name='detail'),
    path('create/', views.MovieCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.MovieUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.MovieDeleteView.as_view(), name='delete'),
    url(r'^search/', views.search, name='search')
]

movies/first/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls',namespace='basic_app'))
]

movies/basic_app/models.py
from django.db import models
from django.urls import reverse
from django.db import models

class Movie(models.Model):
    movie_id = models.PositiveIntegerField(default=True)
    title = models.CharField(max_length=30)
    plot = models.TextField(max_length=360)
    director = models.CharField(max_length=30)
    length = models.CharField(max_length=10)
    released_year = models.IntegerField()
    covers = models.URLField(default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Actor(models.Model):
    name = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, related_name='actors', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Post(models.Model):
    content = models.CharField(max_length = 200)

    def __str__(self):
        return self.content

movies/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from . import models
from .models import Post
from django.db import utils


class IndexView(TemplateView):
    template_name = 'index.html'


class MovieListView(ListView):
    model = models.Movie


class MovieDetailView(DetailView):
    context_object_name = 'movie_detail'
    model = models.Movie
    template_name = 'basic_app/movie_details.html'


class MovieCreateView(CreateView):
    fields = ('title', 'plot', 'director', 'length', 'released_year', 'covers')
    model = models.Movie


class MovieUpdateView(UpdateView):
    fields = ('title', 'plot', 'director', 'length', 'released_year', 'covers')
    model = models.Movie


class MovieDeleteView(DeleteView):
    model = models.Movie
    success_url = reverse_lazy("basic_app:list")


def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entry_query = utils.get_query(query_string, ['title'])
        posts = Post.objects.filter(entry_query).order_by('created')
        return render(request, 'search.html', {'query_string': query_string, 'posts': posts})
    else:
        return render(request, 'search.html', {'query_string': 'Null', 'found_entries': 'Enter a search term'})

movies/basic_app/templates/basic_app/basic_app_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Happy Browsing</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <a class="navbar-brand mb-0 h1" href="{% url 'basic_app:list' %}">Movies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
            <form id="searchform" method="get" action="{{ request.get_host }}/basic_app/search/" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search Movies Here" name="q" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" onclick="searchform.submit()" type="button">Search</button>
            </form>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>


</body>
</html>

movies/basic_app/templates/basic_app/movie_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

    <h1>Delete {{movie.title}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">

        <a href="{% url 'basic_app:detail' pk=movie.pk %}">Cancel</a>
    </form>
{% endblock %}

movies/basic_app/templates/basic_app/movie_details.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

    <div class="jumbotron">
        <h2>{{ movie_detail.title }}</h2>
        <img src="{{ movie_detail.covers }}" alt="" width="250" height="300" style="padding: 20px;">
        <p><b>Plot: </b>{{movie_detail.plot }}</p>
        <p><b>Director: </b> {{movie_detail.director }}</p>
        <p><b>Length: </b> {{movie_detail.length }}</p>
        <p><b>Year: </b> {{movie_detail.released_year }}</p>
        <h5>Stars:</h5>

        {% for actor in movie_detail.actors.all %}
         <p>{{ actor.name }}</p>
        {% endfor %}
    </div>

<div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=movie_detail.pk %}">Update</a></p>
</div>


{% endblock %}

movies/basic_app/templates/basic_app/movie_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<div class="container" align="center">
    <h1>
        {% if not form.instance.pk %}
        Create Movie
        {% else %}
        Update Movie
        {% endif %}
    </h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary", value="Submit">
</form>

</div>
{% endblock %}

movies/basic_app/templates/basic_app/movie_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<div class="container">
    <h1>Welcome to the List of the Movies</h1>
        <ol>
            {% for movie in movie_list %}
            <h2><li><a href="{{ movie.id }}">{{movie.title}}</a></li></h2>
            {% endfor %}
        </ol>
</div>
{% endblock %}

movies/basic_app/templates/basic_app/movie_search.html
{% extends 'basic_app/movie_details.html' %}

{% block body_block %}

<p>Posts containing '{{query_string}}'</p>
{% for post in posts %}
    <div>
        <span> {{ post.created }} </span>
        <a href="{% url 'post_detail' slug=post.slug %}"><h2 class="page-title">{{ post.title }}</h2></a>
        <div class="post">
            {{ post.body|safe }}
        </div>
    </div>
{% endfor %}

{% endblock %}

movies/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Happy Browsing</title>
</head>
<body>

   <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <a class="navbar-brand mb-0 h1" href="{% url 'basic_app:list' %}">Movies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

movies/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}